export const countries = [
  {
    value: 'fr',
    label: 'France',
    code: '+33',
    flag: '🇫🇷',
    format: ['c cc cc cc cc'],
  },
  {
    value: 'be',
    label: 'Belgique',
    code: '+32',
    flag: '🇧🇪',
    format: ['z(z) cc cc cc', 'z ccc cc cc'],
  },
  {
    value: 'de',
    label: 'Allemagne',
    code: '+49',
    flag: '🇩🇪',
    format: ['ccc ccc ccc', '1cc ccc cc ccc'],
  },
  {
    value: 'it',
    label: 'Italie',
    code: '+39',
    flag: '🇮🇹',
    format: ['0c cccc cccc', '3cc ccc cccc'],
  },
  {
    value: 'af',
    label: 'Afghanistan',
    code: '+93',
    flag: '🇦🇫',
    format: ['cc ccc cccc'],
  },
  {
    value: 'za',
    label: 'Afrique du Sud',
    code: '+27',
    flag: '🇿🇦',
    format: ['cc ccc cc cc'],
  },
  {
    value: 'al',
    label: 'Albanie',
    code: '+355',
    flag: '🇦🇱',
    format: ['cccc cccc'],
  },
  {
    value: 'dz',
    label: 'Algérie',
    code: '+213',
    flag: '🇩🇿',
    format: ['cc cc cc cc cc'],
  },
  {
    value: 'ar',
    label: 'Argentine',
    code: '+54',
    flag: '🇦🇷',
    format: ['ccc-cccc', '9 + ccc-cccc'],
  },
  {
    value: 'am',
    label: 'Arménie',
    code: '+374',
    flag: '🇦🇲',
    format: ['cc ccc ccc'],
  },
  {
    value: 'au',
    label: 'Australie',
    code: '+61',
    flag: '🇦🇺',
    format: ['x cccc cccc', '4.. ccc ccc'],
  },
  {
    value: 'at',
    label: 'Autriche',
    code: '+43',
    flag: '🇦🇹',
    format: ['c ccc ccc'],
  },
  {
    value: 'az',
    label: 'Azerbaïdjan',
    code: '+994',
    flag: '🇦🇿',
    format: ['cc ccc cccc'],
  },
  {
    value: 'bg',
    label: 'Bulgarie',
    code: '+359',
    flag: '🇧🇬',
    format: ['cc ccc cccc'],
  },
  {
    value: 'es',
    label: 'Espagne',
    code: '+34',
    flag: '🇪🇸',
    format: ['ccc cc cc cc', '6cc ccc ccc'],
  },
  {
    value: 'ee',
    label: 'Estonie',
    code: '+372',
    flag: '🇪🇪',
    format: ['cc cccc', 'c ccc ccc', '5cc cccc', '5c ccc ccc', '5ccc cccc'],
  },
  {
    value: 'gp',
    label: 'Guadeloupe',
    code: '+590',
    flag: '🇬🇵',
    format: ['590 cc cc cc'],
  },
  {
    value: 'gf',
    label: 'Guyane',
    code: '+594',
    flag: '🇬🇫',
    format: ['594 cc cc cc'],
  },
  {
    value: 'ge',
    label: 'Géorgie',
    code: '+995',
    flag: '🇬🇪',
    format: ['cc ccc cccc'],
  },
  {
    value: 'hk',
    label: 'Hong Kong',
    code: '+852',
    flag: '🇭🇰',
    format: ['cc cc cc cc'],
  },
  {
    value: 'hu',
    label: 'Hongrie',
    code: '+36',
    flag: '🇭🇺',
    format: ['1 ccc cccc', 'cc ccc ccc', '20|30|70 ccc cccc'],
  },
  {
    value: 'kg',
    label: 'Kirghizistan',
    code: '+996',
    flag: '🇰🇬',
    format: ['cc ccc cccc'],
  },
  {
    value: 'lv',
    label: 'Lettonie',
    code: '+371',
    flag: '🇱🇻',
    format: ['cccc cccc'],
  },
  {
    value: 'lt',
    label: 'Lituanie',
    code: '+370',
    flag: '🇱🇹',
    format: ['cc cccc cccc'],
  },
  {
    value: 'mo',
    label: 'Macao',
    code: '+853',
    flag: '🇲🇴',
    format: ['28 cc cc cc', '6c cc cc cc'],
  },
  {
    value: 'mq',
    label: 'Martinique',
    code: '+596',
    flag: '🇲🇶',
    format: ['596 cc cc cc'],
  },
  {
    value: 'yt',
    label: 'Mayotte',
    code: '+262',
    flag: '🇾🇹',
    format: ['262 cc cc cc'],
  },
  {
    value: 'md',
    label: 'Moldavie',
    code: '+373',
    flag: '🇲🇩',
    format: ['cc cccc cccc'],
  },
  {
    value: 'nc',
    label: 'Nouvelle-Calédonie',
    code: '+687',
    flag: '🇳🇨',
    format: ['cc cc cc'],
  },
  {
    value: 'uz',
    label: 'Ouzbékistan',
    code: '+998',
    flag: '🇺🇿',
    format: ['cc ccc cccc'],
  },
  {
    value: 'pl',
    label: 'Pologne',
    code: '+48',
    flag: '🇵🇱',
    format: ['cc ccc cc cc'],
  },
  {
    value: 'pt',
    label: 'Portugal',
    code: '+351',
    flag: '🇵🇹',
    format: ['ccc ccc ccc', '800 ccc ccc', '808 ccc ccc', '7cc ccc ccc'],
  },
  {
    value: 'ro',
    label: 'Roumanie',
    code: '+40',
    flag: '🇷🇴',
    format: ['cc ccc cccc', '70|71|72|73|74|75|76|77 ccc cccc'],
  },
  {
    value: 'ru',
    label: 'Russie',
    code: '+7',
    flag: '🇷🇺',
    format: ['ccc-cc-cc'],
  },
  {
    value: 'cz',
    label: 'République Tchèque',
    code: '+420',
    flag: '🇨🇿',
    format: ['ccc ccc ccc'],
  },
  {
    value: 're',
    label: 'Réunion',
    code: '+262',
    flag: '🇷🇪',
    format: ['262 cc cc cc'],
  },
  {
    value: 'sk',
    label: 'Slovaquie',
    code: '+421',
    flag: '🇸🇰',
    format: ['ccc ccc cccc'],
  },
  {
    value: 'ch',
    label: 'Suisse',
    code: '+41',
    flag: '🇨🇭',
    format: ['cc ccc cc cc', '075|076|077|078|079 ccc cccc'],
  },
  {
    value: 'se',
    label: 'Suède',
    code: '+46',
    flag: '🇸🇪',
    format: ['c cc cc ccc'],
  },
  {
    value: 'tw',
    label: 'Taïwan',
    code: '+886',
    flag: '🇹🇼',
    format: ['c cccc cccc'],
  },
  {
    value: 'tl',
    label: 'Timor oriental',
    code: '+670',
    flag: '🇹🇱',
    format: ['cccc cccc'],
  },
  {
    value: 'ua',
    label: 'Ukraine',
    code: '+380',
    flag: '🇺🇦',
    format: ['cc ccc cccc'],
  },
  {
    value: 'va',
    label: 'Vatican',
    code: '+39',
    flag: '🇻🇦',
    format: ['0c cccc cccc'],
  },
  {
    value: 'us',
    label: 'États-Unis',
    code: '+1',
    flag: '🇺🇸',
    format: ['(ccc) ccc-cccc'],
  },
]
